
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class NQueenControl extends javax.swing.JFrame {

    /**
     * Creates new form NQueenControl
     */
    public NQueenControl() {
        initComponents();
        setLocationRelativeTo(null);
        myBoard = new BoardGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boardSizeField = new javax.swing.JTextField();
        setBoardBtn = new javax.swing.JButton();
        updateSpeedSlider = new javax.swing.JSlider();
        startProcessBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        speedLabel = new javax.swing.JLabel();
        colorS1Btn = new javax.swing.JButton();
        colorS2Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NQueenControl");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        boardSizeField.setText("8");

        setBoardBtn.setBackground(new java.awt.Color(0, 0, 0));
        setBoardBtn.setForeground(new java.awt.Color(255, 255, 255));
        setBoardBtn.setText("Set Board");
        setBoardBtn.setBorder(null);
        setBoardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBoardBtnActionPerformed(evt);
            }
        });

        updateSpeedSlider.setBackground(new java.awt.Color(51, 51, 51));
        updateSpeedSlider.setMaximum(1000);
        updateSpeedSlider.setToolTipText("");
        updateSpeedSlider.setValue(200);
        updateSpeedSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateSpeedSlider.setEnabled(false);
        updateSpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateSpeedSliderStateChanged(evt);
            }
        });

        startProcessBtn.setBackground(new java.awt.Color(0, 0, 0));
        startProcessBtn.setForeground(new java.awt.Color(255, 255, 255));
        startProcessBtn.setText("Start Processing");
        startProcessBtn.setBorder(null);
        startProcessBtn.setEnabled(false);
        startProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcessBtnActionPerformed(evt);
            }
        });

        stopBtn.setBackground(new java.awt.Color(0, 0, 0));
        stopBtn.setForeground(new java.awt.Color(255, 255, 255));
        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueenv3/pause_button_icon.png"))); // NOI18N
        stopBtn.setBorder(null);
        stopBtn.setEnabled(false);
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        speedLabel.setText("200");

        colorS1Btn.setBackground(new java.awt.Color(118, 150, 86));
        colorS1Btn.setForeground(new java.awt.Color(255, 255, 255));
        colorS1Btn.setBorder(null);
        colorS1Btn.setEnabled(false);
        colorS1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorS1BtnActionPerformed(evt);
            }
        });

        colorS2Btn.setBackground(new java.awt.Color(139, 69, 19));
        colorS2Btn.setForeground(new java.awt.Color(255, 255, 255));
        colorS2Btn.setBorder(null);
        colorS2Btn.setEnabled(false);
        colorS2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorS2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boardSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setBoardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startProcessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(colorS1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(colorS2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boardSizeField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(setBoardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(startProcessBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorS2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorS1Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        
        queenLogic.terminateAll();
        queenLogic.joinAll();
        stopBtn.setEnabled(false);
        setBoardBtn.setEnabled(true);
        updateSpeedSlider.setEnabled(false);
        myBoard.dispose();

        colorS1Btn.setEnabled(false);
        colorS2Btn.setEnabled(false);
        


    }//GEN-LAST:event_stopBtnActionPerformed

    private void setBoardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBoardBtnActionPerformed
        try {
            
            boardSize = Integer.parseInt(boardSizeField.getText());
            if(boardSize>20||boardSize<4) throw new NumberFormatException();
            myBoard.setBoard(boardSize, new Color(139, 69, 19), new Color(255, 250, 205));
            myBoard.setVisible(true);
            
            startProcessBtn.setEnabled(true);
            updateSpeedSlider.setEnabled(true);
            colorS1Btn.setEnabled(true);
            colorS2Btn.setEnabled(true);
            updateSpeed = updateSpeedSlider.getValue();
            queenLogic = new NQueens(boardSize,updateSpeed,myBoard);
            queenLogic.initQueen();
            

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid Input ");
        }
    }//GEN-LAST:event_setBoardBtnActionPerformed

    private void updateSpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateSpeedSliderStateChanged
        updateSpeed = updateSpeedSlider.getValue();
        speedLabel.setText("" + updateSpeed);
        queenLogic.setUpdateTime(updateSpeed);

    }//GEN-LAST:event_updateSpeedSliderStateChanged

    private void startProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcessBtnActionPerformed
        colorS1Btn.setEnabled(false);
        colorS2Btn.setEnabled(false);
        startProcessBtn.setEnabled(false);
        setBoardBtn.setEnabled(false);
        stopBtn.setEnabled(true);
        queenLogic.startQueen();


    }//GEN-LAST:event_startProcessBtnActionPerformed

    private void colorS1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorS1BtnActionPerformed
        myBoard.setBoardColor(new Color(118, 150, 86), new Color(238, 238, 210));
    }//GEN-LAST:event_colorS1BtnActionPerformed

    private void colorS2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorS2BtnActionPerformed
        myBoard.setBoardColor(new Color(139, 69, 19), new Color(255, 250, 205));
    }//GEN-LAST:event_colorS2BtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NQueenControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NQueenControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NQueenControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NQueenControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
                new NQueenControl().setVisible(true);
            //}
        //});
    }
    
    
    private int boardSize = 8;
    private int updateSpeed;
    private BoardGUI myBoard;
    private NQueens queenLogic;
    private Icon pauseIcon = new ImageIcon("pause_button_icon.png");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boardSizeField;
    private javax.swing.JButton colorS1Btn;
    private javax.swing.JButton colorS2Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setBoardBtn;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JButton startProcessBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JSlider updateSpeedSlider;
    // End of variables declaration//GEN-END:variables
}
